const plantsData = [
    {
        id: 1,
        name: 'Роза',
        scientific: 'Rosa spp.',
        category: 'flowers',
        description: 'Популярное садовое растение с ароматными цветами.',
        image: 'img/rose.png',
        tags: ['☀️ Свет', '💧 Умеренный', '🌱 Средний уход'],
        watering: 'Поливать 2-3 раза в неделю летом, зимой реже. Не заливать!',
        wateringInterval: 3,
        lighting: 'Яркий рассеянный свет, полутень.',
        transplant: 'Пересаживать весной раз в 2-3 года.',
        transplantInterval: 730,
        poisonous: 'Не ядовито.',
        features: 'Любит опрыскивание, не переносит сквозняки.'
    },
    {
        id: 2,
        name: 'Кактус',
        scientific: 'Cactaceae',
        category: 'succulents',
        description: 'Неприхотливое растение, идеально для начинающих.',
        image: 'img/cactaceae.png',
        tags: ['☀️ Яркий свет', '💧 Редкий', '🌱 Легкий уход'],
        watering: 'Поливать 1 раз в 2-3 недели летом, зимой раз в месяц.',
        wateringInterval: 14,
        lighting: 'Яркий солнечный свет.',
        transplant: 'Пересаживать раз в 2-3 года весной.',
        transplantInterval: 730,
        poisonous: 'Не ядовит.',
        features: 'Не любит переувлажнения, нужен дренаж.'
    },
    {
        id: 3,
        name: 'Орхидея',
        scientific: 'Orchidaceae',
        category: 'flowers',
        description: 'Изысканное растение с экзотическими цветами.',
        image: 'img/orchidaceae.png',
        tags: ['☀️ Рассеянный', '💧 Умеренный', '🌱 Высокий уход'],
        watering: 'Поливать раз в 5-7 дней, только когда субстрат просох.',
        wateringInterval: 6,
        lighting: 'Яркий рассеянный свет, без прямых солнечных лучей.',
        transplant: 'Пересаживать раз в 2 года после цветения.',
        transplantInterval: 730,
        poisonous: 'Не ядовита.',
        features: 'Любит влажность, нуждается в опрыскивании.'
    },
    {
        id: 4,
        name: 'Базилик',
        scientific: 'Ocimum basilicum',
        category: 'herbs',
        description: 'Ароматная пряная трава для кулинарии.',
        image: 'img/basilicum.png',
        tags: ['☀️ Яркий свет', '💧 Умеренный', '🌱 Простой уход'],
        watering: 'Поливать ежедневно в жаркую погоду, не пересушивать.',
        wateringInterval: 1,
        lighting: 'Яркий солнечный свет 6-8 часов в день.',
        transplant: 'Не требует пересадки, выращивается из семян.',
        transplantInterval: 9999,
        poisonous: 'Не ядовит.',
        features: 'Любит тепло, регулярно прищипывайте для роста.'
    },
    {
        id: 5,
        name: 'Пальма',
        scientific: 'Arecaceae',
        category: 'palms',
        description: 'Эффектное комнатное дерево с пышной кроной.',
        image: 'img/palm.png',
        tags: ['☀️ Рассеянный', '💧 Обильный', '🌱 Средний уход'],
        watering: 'Поливать обильно, но редко. Давать земле просохнуть.',
        wateringInterval: 7,
        lighting: 'Яркий рассеянный свет, полутень.',
        transplant: 'Пересаживать весной раз в 3-4 года.',
        transplantInterval: 1095,
        poisonous: 'Не ядовита.',
        features: 'Любит опрыскивание, протирайте листья от пыли.'
    },
    {
        id: 6,
        name: 'Алоэ вера',
        scientific: 'Aloe vera',
        category: 'succulents',
        description: 'Лечебное растение с полезными свойствами.',
        image: 'img/aloevera.png',
        tags: ['☀️ Яркий свет', '💧 Редкий', '🌱 Легкий уход'],
        watering: 'Поливать раз в 2-3 недели, зимой раз в месяц.',
        wateringInterval: 14,
        lighting: 'Яркий солнечный свет.',
        transplant: 'Пересаживать весной раз в 2 года.',
        transplantInterval: 730,
        poisonous: 'Не ядовито, но не употреблять внутрь.',
        features: 'Сок обладает целебными свойствами.'
    },
    {
        id: 7,
        name: 'Монстера',
        scientific: 'Monstera deliciosa',
        category: 'trees',
        description: 'Тропическое растение с резными листьями.',
        image: 'img/monstera.png',
        tags: ['☀️ Рассеянный', '💧 Умеренный', '🌱 Средний уход'],
        watering: 'Поливать обильно летом, умеренно зимой.',
        wateringInterval: 5,
        lighting: 'Яркий рассеянный свет.',
        transplant: 'Пересаживать весной раз в 2 года.',
        transplantInterval: 730,
        poisonous: 'Ядовито! Сок раздражает кожу и слизистые.',
        features: 'Нуждается в опоре, любит влажность.'
    },
    {
        id: 8,
        name: 'Лаванда',
        scientific: 'Lavandula',
        category: 'herbs',
        description: 'Ароматное растение с успокаивающим запахом.',
        image: 'img/lavande.png',
        tags: ['☀️ Яркий свет', '💧 Редкий', '🌱 Простой уход'],
        watering: 'Поливать умеренно, не переувлажнять.',
        wateringInterval: 5,
        lighting: 'Яркий солнечный свет.',
        transplant: 'Пересаживать весной раз в 2-3 года.',
        transplantInterval: 730,
        poisonous: 'Не ядовита.',
        features: 'Любит известковую почву, не переносит застоя воды.'
    }
];